### ISSUE TITLE
Attribute Name's length upper bounds

### ISSUE THREAD

**Issue by thomas-fossati** [core-wg/core-target-attr#7]
There are none at the moment, so this is left for the expert to decide.
Does it make sense setting an upper bound -- say, 16 or 32?

**Comment by cabo** [comment]
Interesting discussion over at netmod:

Epic discussion thread starts at
Archived-At: <https://mailarchive.ietf.org/arch/msg/cfrg/xEo-qO__Qe2jc6JCCy0eAZC6oM0>

Artificial hard limits come back to bite you...
https://www.rfc-editor.org/errata/eid7251

I think the discussion has been against instituting some hard limit -- that either isn't very hard or it will bite when a longer name is needed for some reason we can't imagine just yet.
